### ISSUE TITLE
Collision Detection

### ISSUE THREAD

**Issue by AJStrizzy** [AJStrizzy/Space-Invaders#4]
The function successfully detects collisions, but when after the alien grid nears the bottom of the screen the whole grid flies off.

function boom() {
    for(a = 0; a < arrAliens.length; a++) {
       
        for(b = 0; b < arrBullets.length; b++) {
           if(arrBullets[b].x >= arrAliens[a].x - 3 && arrBullets[b].x <=arrAliens[a].x +17
            && arrBullets[b].y >= arrAliens[a].y - 5 && arrBullets[b].y <=arrAliens[a].y +9) {
                arrAliens.splice(a,1)
                arrBullets.splice(b,1)
            }
        }
    }
}

**Comment by pmacaluso3** [comment]
When you say fly off, do you mean that they continue off the screen at their normal speed, or that they speed up? Is there any collision detection in place to detect when the aliens hit the bottom of the screen?
